### ISSUE TITLE
一行 css 实现移动端适配

### ISSUE THREAD

**Issue by cjg1122** [cjg1122/blog#23]
```css
html {
  /* 375 是设计稿的宽度 */
  font-size: calc(100vw * 16 / 375);
}
```

```css
html {
  /* 可以指定最大值 */
  font-size: min(calc(100vw * 16 / 375), 32px);
  max-width: 750px;
}
```

### 计算原理

![image](https://github.com/user-attachments/assets/63aa2c1c-76c4-4c77-9a46-8027df8b3ad5)
