### ISSUE TITLE
CSS 优先级（Specificity）

### ISSUE THREAD

**Issue by cjg1122** [cjg1122/blog#45]
CSS 优先级（Specificity）是用来决定当多个 CSS 规则作用于同一个元素时，哪一个规则会被应用的机制。优先级是通过一个特定的算法计算出来的，主要根据选择器的类型来计算。具体规则如下：

1. **内联样式**（Inline styles）：这些样式直接写在 HTML 元素的 `style` 属性中，优先级最高，例如：`<div style="color: red;">`。

2. **ID 选择器**（ID selectors）：例如 `#id`。

3. **类选择器、属性选择器和伪类选择器**（Class selectors, Attribute selectors, and Pseudo-classes）：例如 `.class`、`[type="text"]`、`:hover`。

4. **元素选择器和伪元素选择器**（Element selectors and Pseudo-elements）：例如 `div`、`p`、`::before`。

5. **通配选择器**（universal selector）（*）**关系选择器**（combinator）（+、>、~、" "、||）和 **否定伪类**（negation pseudo-class）（:not()）对优先级没有影响。（但是，在 :not() 内部声明的选择器会影响优先级）。

### 优先级的计算方法

优先级是通过一个四部分的数字来表示的：`(a, b, c, d)`，其中：

- `a`：如果是内联样式，则为 1，否则为 0。
- `b`：ID 选择器的数量。
- `c`：类选择器、属性选择器和伪类选择器的数量。
- `d`：元素选择器和伪元素选择器的数量。

例如：

- 内联样式：`(1, 0, 0, 0)`
- `#id`: `(0, 1, 0, 0)`
- `.class`: `(0, 0, 1, 0)`
- `div`: `(0, 0, 0, 1)`

### 示例

假设有以下 CSS 规则：

```css
/* 1 */
div {
    color: black;
}

/* 2 */
#main {
    color: blue;
}

/* 3 */
.content {
    color: green;
}

/* 4 */
div.content {
    color: yellow;
}

/* 5 */
#main .content {
    color: red;
}
```

如果 HTML 代码如下：

```html
<div id="main" class="content">Hello World</div>
```

计算每个选择器的优先级：

1. `div` 的优先级是 `(0, 0, 0, 1)`
2. `#main` 的优先级是 `(0, 1, 0, 0)`
3. `.content` 的优先级是 `(0, 0, 1, 0)`
4. `div.content` 的优先级是 `(0, 0, 1, 1)`
5. `#main .content` 的优先级是 `(0, 1, 1, 0)`

因此，最终应用的样式是 `#main .content` 的样式，即 `color: red;`，因为它的优先级 `(0, 1, 1, 0)` 最高。

### !important

`!important` 声明会覆盖上述所有优先级规则。即使一个选择器的优先级较低，但如果它使用了 `!important`，它的样式会覆盖所有其他没有使用 `!important` 的样式。

例如：

```css
div {
    color: black !important;
}
```

即使有其他优先级更高的选择器，这条规则仍然会被应用。
