### ISSUE TITLE
css 属性值 initial、unset 和 revert

### ISSUE THREAD

**Issue by cjg1122** [cjg1122/blog#52]
在 CSS 中，`initial`、`unset` 和 `revert` 是用于设置 CSS 属性值的特殊关键字。它们在不同的上下文中具有不同的行为。

### `initial`

`initial` 关键字将 CSS 属性设置为其初始值。初始值是属性在没有任何样式规则应用时的默认值。换句话说，`initial` 会将属性重置为其规范中的默认值。

#### 示例：
```css
/* 假设我们有一个段落元素 */
p {
  color: red; /* 将文本颜色设置为红色 */
}

p.reset {
  color: initial; /* 将文本颜色重置为初始值，通常为黑色 */
}
```

### `unset`

`unset` 关键字将 CSS 属性重置为其继承值（如果该属性是可继承的）或其初始值（如果该属性是不可继承的）。它结合了 `inherit` 和 `initial` 的行为。

#### 示例：
```css
/* 假设我们有一个段落元素 */
p {
  color: red; /* 将文本颜色设置为红色 */
}

p.unset {
  color: unset; /* 如果 color 是可继承的，则继承父元素的值，否则重置为初始值 */
}
```

### `revert`

`revert` 关键字将 CSS 属性重置为用户代理样式表（浏览器默认样式）或用户样式表中定义的值，而不是作者样式表中的值。它会撤销作者样式表中的任何变化，恢复为浏览器或用户定义的默认值。

#### 示例：
```css
/* 假设我们有一个段落元素 */
p {
  color: red; /* 将文本颜色设置为红色 */
}

p.revert {
  color: revert; /* 撤销作者样式表中的颜色设置，恢复为浏览器默认样式 */
}
```

### 对比总结

- **`initial`**: 将属性设置为其规范中的初始值。
- **`unset`**: 如果属性是可继承的，则继承父元素的值；否则，设置为初始值。
- **`revert`**: 撤销作者样式表中的设置，恢复为用户代理样式表或用户样式表中的值。

### 实际应用示例

假设我们有如下 HTML 和 CSS：

```html
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      color: blue; /* 设置全局文本颜色为蓝色 */
    }
    p {
      color: red; /* 将段落文本颜色设置为红色 */
    }
    .initial {
      color: initial; /* 重置为初始值 */
    }
    .unset {
      color: unset; /* 如果可继承，则继承父元素的值，否则重置为初始值 */
    }
    .revert {
      color: revert; /* 撤销作者样式表中的设置，恢复为浏览器默认样式 */
    }
  </style>
</head>
<body>
  <p class="initial">This is a paragraph with initial.</p>
  <p class="unset">This is a paragraph with unset.</p>
  <p class="revert">This is a paragraph with revert.</p>
</body>
</html>
```

在这个例子中：

- `.initial` 类会将段落的颜色重置为初始值（通常为黑色）。
- `.unset` 类会将段落的颜色继承自父元素 `<body>`，即蓝色。
- `.revert` 类会将段落的颜色恢复为浏览器默认样式（通常为黑色），因为没有用户样式表定义。

通过这些关键字，开发者可以更灵活地控制 CSS 属性的值，适应不同的需求和上下文。
