### ISSUE TITLE
CSS 函数 calc() 会引起重排重绘吗

### ISSUE THREAD

**Issue by cjg1122** [cjg1122/blog#63]
CSS 函数 `calc()` 本身不会直接引起重排（reflow）或重绘（repaint），因为它只是定义了一个计算方式，用于动态计算 CSS 属性的值。重排和重绘的触发主要取决于使用 `calc()` 的 CSS 属性以及在何种情况下应用这些属性。

### 重排（Reflow）
重排是指浏览器重新计算元素的位置和尺寸的过程。会引起重排的常见 CSS 属性包括：

- `width`
- `height`
- `margin`
- `padding`
- `border`
- `display`
- `position`

如果这些属性使用了 `calc()`，并且这些属性的值发生了变化（例如窗口大小变化、元素内容变化等），那么会触发重排。

### 重绘（Repaint）
重绘是指浏览器重新绘制元素的外观，但不涉及元素的布局变化。会引起重绘的常见 CSS 属性包括：

- `color`
- `background-color`
- `visibility`
- `outline`

如果这些属性使用了 `calc()`，并且这些属性的值发生了变化，那么会触发重绘。

### 示例
假设有以下 CSS 规则：

```css
.element {
  width: calc(100% - 20px);
  height: calc(50vh - 10px);
  background-color: calc(50% + 50%);
}
```

- `width` 和 `height` 使用了 `calc()`，如果窗口大小改变，会触发重排。
- `background-color` 使用了 `calc()`，如果这个值变化，会触发重绘。

### 总结
`calc()` 函数本身不会直接引起重排或重绘，但使用 `calc()` 的 CSS 属性在特定情况下（例如值变化）会触发重排或重绘。因此，是否会引起重排或重绘，主要取决于使用 `calc()` 的具体 CSS 属性以及在何种情况下应用这些属性。
